name: workflow cd

on:
 workflow_call:
  inputs:
    target: 
      type: string 
      required: true

jobs:
  get_image:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Set Image Tag Action
        uses: ./.github/actions/get-image-tag
        id: get_tag
        with:
          target: ${{ inputs.target }}

  deploy:
    runs-on: ubuntu-latest
    needs: get_image
    environment: ${{ inputs.target }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull and Run Docker Image
      uses: ./.github/actions/pull-and-run-image
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        image_tag: ${{ needs.get_image.outputs.tag }}

    - name: Curl Tests
      if: ${{ inputs.target == 'prod' }}
      uses: ./.github/actions/curl-tests