name: Production Environment Workflow Caller

on:
  push:
    branches: main
  pull_request:
    branches: main
    types: [closed]

jobs:
  run_ci_prod:
    uses: ./.github/workflows/workflow-ci.yml
    secrets: inherit
    with:
      target: prod

  run_cd_prod:
    needs: run_ci_prod    
    uses: ./.github/workflows/workflow-cd.yml
    secrets: inherit
    with:
      target: prod
        

      